import { discoverUserJourneys } from "./journeys.js";
import { discoverUnitTestTargets } from "./unitDiscovery.js";
import { discoverApiEndpoints } from "./apiDiscovery.js";
import { createSonarProperties } from "./sonarDiscovery.js";
import { createTrivyIgnore } from "./securityDiscovery.js";

const GITLEAKS_CONFIG = `# Generated by repo-aware-testing-agent.
# Gitleaks scans the working tree (not git history) for committed/staged
# secrets. qa:secrets runs:
#   gitleaks detect --report-format json --report-path qa-results/gitleaks.json --no-git --no-banner --exit-code 0
# Severity gating is applied by scripts/qa-report.mjs.
#
# This file is a place to extend gitleaks' default rules. The default rules
# already cover AWS, GCP, Slack, GitHub, OpenAI, Anthropic, Stripe, JWTs,
# and dozens more. Add per-project allowlists below as needed.
#
# Example allowlist (skip the example env file from scanning):
# [allowlist]
#   description = "example env files"
#   paths = ['''\\.env\\.example$''', '''(^|/)env\\.example$''']
`;

const PLAYWRIGHT_CONFIG = `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  timeout: 60_000,
  retries: process.env.CI ? 1 : 0,
  reporter: [['list'], ['html', { open: 'never' }], ['json', { outputFile: 'playwright-report/results.json' }]],
  use: {
    baseURL: process.env.QA_BASE_URL || 'http://localhost:3000',
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure'
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }]
});
`;

const PLAYWRIGHT_SMOKE = `import { expect, test } from '@playwright/test';

test('smoke: configured page loads', async ({ page }) => {
  await page.goto(process.env.QA_SMOKE_PATH || '/', { waitUntil: 'domcontentloaded' });
  await expect(page.locator('body')).not.toBeEmpty();
});
`;

const PLAYWRIGHT_E2E = `import { expect, test } from '@playwright/test';

test('e2e: custom critical user journey', async ({ page }) => {
  // Step 1: Verify Homepage loads
  await page.goto(process.env.QA_E2E_PATH || '/', { waitUntil: 'domcontentloaded' });
  await expect(page.locator('body')).toBeVisible();

  // Step 2: Verify About page loads
  await page.goto('/about', { waitUntil: 'domcontentloaded' });
  await expect(page.locator('body')).toBeVisible();

  // Step 3: Verify Contact page loads
  await page.goto('/contact', { waitUntil: 'domcontentloaded' });
  await expect(page.locator('body')).toBeVisible();
});
`;

function createPlaywrightJourneySpec(journeys, enrichment = new Map()) {
  const rows = journeys.map((journey) => ({
    title: journey.title,
    path: journey.path,
    env: journey.env,
    source: journey.source,
    dynamic: journey.dynamic,
  }));

  const enrichedObj = {};
  for (const [route, value] of enrichment) enrichedObj[route] = value;

  return `import { expect, test } from '@playwright/test';

const journeys = ${JSON.stringify(rows, null, 2)};

// LLM-derived per-route assertions (when ANTHROPIC_API_KEY is set during
// generation). Each entry: { description, expected: [{kind, text?, name?, level?}] }.
const ENRICHED = ${JSON.stringify(enrichedObj, null, 2)};

function escapeRegex(text) {
  return String(text || '').replace(/[.*+?^\${}()|[\\]\\\\]/g, '\\\\$&');
}

async function checkEnrichment(page, assertion) {
  const pattern = (text) => new RegExp(escapeRegex(text), 'i');
  if (assertion.kind === 'heading' && assertion.text) {
    await expect(page.getByRole('heading', { name: pattern(assertion.text) }).first()).toBeVisible();
  } else if (assertion.kind === 'heading' && assertion.level) {
    await expect(page.locator('h' + assertion.level).first()).toBeVisible();
  } else if (assertion.kind === 'text' && assertion.text) {
    await expect(page.getByText(pattern(assertion.text)).first()).toBeVisible();
  } else if (assertion.kind === 'link' && assertion.name) {
    await expect(page.getByRole('link', { name: pattern(assertion.name) }).first()).toBeVisible();
  } else if (assertion.kind === 'button' && assertion.name) {
    await expect(page.getByRole('button', { name: pattern(assertion.name) }).first()).toBeVisible();
  } else if (assertion.kind === 'image') {
    await expect(page.getByRole('img').first()).toBeVisible();
  }
}

async function exerciseVisibleFormControls(page) {
  const textInputs = page.locator('input:not([type]), input[type="text"], input[type="search"], input[type="email"], input[type="tel"], textarea');
  for (let index = 0; index < await textInputs.count(); index += 1) {
    const input = textInputs.nth(index);
    if (await input.isVisible().catch(() => false)) {
      await input.fill('qa automation');
    }
  }

  const passwordInputs = page.locator('input[type="password"]');
  for (let index = 0; index < await passwordInputs.count(); index += 1) {
    const input = passwordInputs.nth(index);
    if (await input.isVisible().catch(() => false)) {
      await input.fill('QaAutomation123!');
    }
  }

  const numberInputs = page.locator('input[type="number"]');
  for (let index = 0; index < await numberInputs.count(); index += 1) {
    const input = numberInputs.nth(index);
    if (await input.isVisible().catch(() => false)) {
      await input.fill('1');
    }
  }

  const selects = page.locator('select');
  for (let index = 0; index < await selects.count(); index += 1) {
    const select = selects.nth(index);
    if (await select.isVisible().catch(() => false)) {
      const values = await select.locator('option').evaluateAll((options) => options.map((option) => option.value).filter(Boolean));
      if (values[0]) await select.selectOption(values[0]);
    }
  }
}

for (const journey of journeys) {
  test(\`journey: \${journey.title}\`, async ({ page }) => {
    const path = process.env[journey.env] || journey.path;
    await page.goto(path, { waitUntil: 'domcontentloaded' });
    await expect(page.locator('body')).toBeVisible();
    const enriched = ENRICHED[journey.path];
    if (enriched && Array.isArray(enriched.expected) && enriched.expected.length) {
      for (const assertion of enriched.expected) await checkEnrichment(page, assertion);
    } else {
      await expect(page.locator('body')).not.toBeEmpty();
      await exerciseVisibleFormControls(page);
    }
  });
}
`;
}

function createVisualSpec(journeys) {
  const rows = journeys.map((journey) => ({ title: journey.title, path: journey.path, env: journey.env }));
  return `import { expect, test } from '@playwright/test';

const journeys = ${JSON.stringify(rows, null, 2)};

// Visual regression. First run records baselines under
// tests/visual/__screenshots__/. Subsequent runs diff against the baseline
// and fail when pixels exceed QA_VISUAL_MAX_DIFF_PIXELS (default 100) or
// QA_VISUAL_MAX_DIFF_RATIO (default 0.01). Re-record with:
//   npx playwright test tests/visual --update-snapshots

function slug(routePath) {
  return (routePath || 'root').replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'root';
}

const maxDiffPixels = Number(process.env.QA_VISUAL_MAX_DIFF_PIXELS || 100);
const maxDiffPixelRatio = Number(process.env.QA_VISUAL_MAX_DIFF_RATIO || 0.01);

for (const journey of journeys) {
  test(\`visual: \${journey.title}\`, async ({ page }) => {
    const targetPath = process.env[journey.env] || journey.path;
    await page.goto(targetPath, { waitUntil: 'networkidle' });
    await page.waitForLoadState('domcontentloaded');
    // Hide caret + disable animations to keep baselines stable.
    await page.addStyleTag({ content: '*, *::before, *::after { animation: none !important; transition: none !important; caret-color: transparent !important; }' });
    await expect(page).toHaveScreenshot(slug(journey.path) + '.png', {
      fullPage: true,
      animations: 'disabled',
      maxDiffPixels,
      maxDiffPixelRatio,
    });
  });
}
`;
}

function createAxeSpec(journeys) {
  const rows = journeys.map((journey) => ({ title: journey.title, path: journey.path, env: journey.env }));
  return `import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const journeys = ${JSON.stringify(rows, null, 2)};

const outDir = path.join(process.cwd(), 'qa-results', 'axe');
mkdirSync(outDir, { recursive: true });

// QA_A11Y_FAIL_ON controls which impact levels fail the test.
// Default: serious + critical only. Set to "minor,moderate,serious,critical" to fail on everything.
const failOn = (process.env.QA_A11Y_FAIL_ON || 'serious,critical').split(',').map((s) => s.trim()).filter(Boolean);

function slug(routePath) {
  return (routePath || 'root').replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'root';
}

for (const journey of journeys) {
  test(\`a11y: \${journey.title}\`, async ({ page }) => {
    const targetPath = process.env[journey.env] || journey.path;
    await page.goto(targetPath, { waitUntil: 'domcontentloaded' });
    const results = await new AxeBuilder({ page }).analyze();
    writeFileSync(
      path.join(outDir, slug(journey.path) + '.json'),
      JSON.stringify({
        path: journey.path,
        title: journey.title,
        violations: results.violations,
        incomplete: results.incomplete,
        passes: results.passes.length,
      }, null, 2),
    );
    const blocking = results.violations.filter((v) => failOn.includes(v.impact));
    expect(
      blocking,
      'a11y violations (' + failOn.join('/') + ') on ' + journey.path + ': ' + blocking.map((v) => v.id + ':' + v.help).join(', ')
    ).toEqual([]);
  });
}
`;
}

const VITEST = `import { describe, it, expect } from 'vitest';

describe('Custom QA Logic Verification', () => {
  it('should successfully run custom unit tests', () => {
    const baseline = 100;
    const modifier = 50;
    expect(baseline + modifier).toBe(150);
  });
  
  it('should handle string parsing properly', () => {
    const data = "test-case-001";
    expect(data.split('-')).toHaveLength(3);
  });
});
`;

function createGeneratedUnitTests(targets) {
  return `import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const manifest = ${JSON.stringify(targets, null, 2)};

function repoPath(file) {
  return path.join(root, file);
}

describe('QA generated unit coverage manifest', () => {
  it('keeps package scripts available for the detected QA workflow', () => {
    const pkg = JSON.parse(readFileSync(repoPath('package.json'), 'utf8'));
    for (const script of manifest.packageScripts) {
      expect(pkg.scripts, 'package script "' + script + '" should exist').toHaveProperty(script);
    }
  });

  it.each(manifest.sourceFiles)('source file exists: %s', (file) => {
    expect(existsSync(repoPath(file))).toBe(true);
  });

  it.each(manifest.configFiles)('config file exists: %s', (file) => {
    expect(existsSync(repoPath(file))).toBe(true);
  });

  it.each(manifest.routeFiles)('ui route file exists: %s', (file) => {
    expect(existsSync(repoPath(file))).toBe(true);
  });

  it.each(manifest.apiFiles)('api unit target exists: %s', (file) => {
    expect(existsSync(repoPath(file))).toBe(true);
  });

  it.each(manifest.componentFiles)('component unit target exists: %s', (file) => {
    expect(existsSync(repoPath(file))).toBe(true);
  });

  it.each(manifest.envFiles)('environment contract file exists: %s', (file) => {
    expect(existsSync(repoPath(file))).toBe(true);
  });

  it('records whether large target groups were truncated', () => {
    expect(manifest.truncated).toEqual(expect.any(Object));
  });
});
`;
}

function createPostmanCollection(endpoints) {
  const item = endpoints.map((endpoint) => ({
    name: `${endpoint.method} ${endpoint.path}`,
    request: {
      method: endpoint.method,
      url: `{{baseUrl}}{{${endpoint.env}}}`,
      description: `Generated from ${endpoint.source}. Validates ${endpoint.name}.`,
    },
    event: [
      {
        listen: "test",
        script: {
          type: "text/javascript",
          exec: [
            `pm.test('${endpoint.method} ${endpoint.path} does not return server error', function () {`,
            "  pm.expect(pm.response.code).to.be.below(500);",
            "});",
            `pm.test('${endpoint.method} ${endpoint.path} responds within 2s', function () {`,
            "  pm.expect(pm.response.responseTime).to.be.below(2000);",
            "});",
            "if ((pm.response.headers.get('content-type') || '').includes('application/json')) {",
            `  pm.test('${endpoint.method} ${endpoint.path} returns valid JSON when advertised', function () {`,
            "    pm.response.json();",
            "  });",
            "}",
          ],
        },
      },
    ],
  }));

  return `${JSON.stringify({
    info: {
      name: "QA API Contract",
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
    },
    item,
  }, null, 2)}\n`;
}

function createPostmanEnv(endpoints) {
  return `${JSON.stringify({
    name: "QA Local",
    values: [
      { key: "baseUrl", value: "http://localhost:3000", enabled: true },
      ...endpoints.map((endpoint) => ({ key: endpoint.env, value: endpoint.path, enabled: true })),
    ],
  }, null, 2)}\n`;
}

function createK6Script(endpoints) {
  const targets = endpoints.map((endpoint) => ({
    name: endpoint.name,
    method: endpoint.method,
    path: endpoint.path,
    env: endpoint.env,
    source: endpoint.source,
  }));

  return `import http from 'k6/http';
import { check, sleep } from 'k6';
import { group } from 'k6';

export const options = {
  scenarios: {
    smoke: {
      executor: 'constant-vus',
      vus: Number(__ENV.QA_K6_VUS || 5),
      duration: __ENV.QA_K6_DURATION || '10s',
    },
    stress: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: '5s', target: 20 },
        { duration: '10s', target: 20 },
        { duration: '5s', target: 0 },
      ],
      gracefulRampDown: '5s',
    },
  },
  thresholds: {
    http_req_failed: ['rate<0.05'],
    http_req_duration: ['p(95)<2000'],
    checks: ['rate>0.95']
  }
};

const endpoints = ${JSON.stringify(targets, null, 2)};

export default function () {
  const baseUrl = __ENV.QA_K6_BASE_URL || __ENV.QA_API_BASE_URL || 'http://localhost:3000';
  for (const endpoint of endpoints) {
    const path = __ENV[endpoint.env] || endpoint.path;
    const url = baseUrl.replace(/\\/$/, '') + path;
    group(endpoint.method + ' ' + path, () => {
      const res = http.request(endpoint.method, url);
      check(res, {
        'status is below 500': (r) => r.status < 500,
        'response completed under 1s': (r) => r.timings.duration < 1000,
      });
    });
  }
  sleep(1);
}
`;
}

const STAGE_PROFILES = {
  "qa:unit": {
    tier: "zero-infra",
    touches: ["src/", "app/", "components/", "lib/", "tests/unit/", "package.json"],
  },
  "qa:security": {
    tier: "zero-infra",
    touches: ["package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "Dockerfile", "Cargo.toml", "go.mod", "go.sum", "pyproject.toml", "Pipfile", "pom.xml", "build.gradle"],
  },
  "qa:secrets": {
    tier: "zero-infra",
    touches: [""],
  },
  "qa:sast": {
    tier: "zero-infra",
    touches: ["src/", "app/", "lib/", "pages/", "components/", "scripts/", "server/"],
  },
  "qa:smoke": {
    tier: "needs-app",
    touches: ["src/", "app/", "pages/", "components/", "tests/smoke/"],
  },
  "qa:journeys": {
    tier: "needs-app",
    touches: ["src/", "app/", "pages/", "components/", "tests/e2e/"],
  },
  "qa:e2e": {
    tier: "needs-app",
    touches: ["src/", "app/", "pages/", "components/", "tests/e2e/"],
  },
  "qa:a11y": {
    tier: "needs-app",
    touches: ["src/", "app/", "pages/", "components/", "tests/a11y/"],
  },
  "qa:visual": {
    tier: "needs-app",
    touches: ["src/", "app/", "pages/", "components/", "tests/visual/"],
  },
  "qa:api": {
    tier: "needs-app",
    touches: ["src/api/", "src/routes/", "src/controllers/", "pages/api/", "app/api/", "postman/"],
  },
  "qa:perf": {
    tier: "needs-app",
    touches: ["src/api/", "src/routes/", "src/controllers/", "pages/api/", "app/api/", "tests/performance/"],
  },
  "qa:quality": {
    tier: "external-service",
    envVar: "SONAR_HOST_URL",
    touches: ["src/", "app/", "lib/"],
  },
};

function buildProfileMap(order) {
  const map = {};
  for (const script of order) {
    if (STAGE_PROFILES[script]) map[script] = STAGE_PROFILES[script];
  }
  return map;
}

function createQaRunAll(order) {
  const profile = buildProfileMap(order);
  return `#!/usr/bin/env node
// Auto-generated by repo-aware-testing-agent.
// Classifies stages into zero-infra (parallel), needs-app (sequenced with managed dev server),
// and external-service (gated by env). See README for env vars and CLI flags.
import { spawn } from 'node:child_process';
import { createWriteStream, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const RESULTS_DIR = path.join(ROOT, 'qa-results');

// Clear stale artifacts from prior runs so the consolidated report reflects
// only this invocation. Honours QA_KEEP_ARTIFACTS=1 for CI archival use.
if (process.env.QA_KEEP_ARTIFACTS !== '1') {
  for (const dir of [RESULTS_DIR, path.join(ROOT, 'playwright-report'), path.join(ROOT, 'test-results')]) {
    rmSync(dir, { recursive: true, force: true });
  }
}
mkdirSync(RESULTS_DIR, { recursive: true });

const pkg = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const STAGE_PROFILE = ${JSON.stringify(profile, null, 2)};
const ORDER = ${JSON.stringify(order, null, 2)};

const argv = process.argv.slice(2);
function flag(name) { const i = argv.indexOf(name); return i >= 0 && argv[i + 1] ? argv[i + 1] : null; }
function has(name) { return argv.includes(name); }

const onlyArg = flag('--only');
const skipArg = flag('--skip');
const failOn = flag('--fail-on') || process.env.QA_FAIL_ON || 'high';
const changedMode = has('--changed') || process.env.QA_CHANGED === '1';
const skipApp = has('--skip-app-server') || process.env.QA_SKIP_APP === '1';
const stageTimeoutMs = Number(process.env.QA_STAGE_TIMEOUT_MS) || 10 * 60 * 1000;
const healthTimeoutMs = Number(process.env.QA_HEALTH_TIMEOUT_MS) || 90 * 1000;
const baseUrl = process.env.QA_BASE_URL || 'http://localhost:3000';

const SEVERITY_RANK = { low: 0, medium: 1, high: 2, critical: 3 };
const failThreshold = SEVERITY_RANK[failOn] ?? SEVERITY_RANK.high;

const results = [];

function record(script, status, extra = {}) {
  results.push({ script, tier: STAGE_PROFILE[script]?.tier || 'unknown', status, ...extra });
}

function classify(script) {
  if (!pkg.scripts?.[script]) return { ok: false, reason: 'script not present' };
  if (onlyArg && !onlyArg.split(',').includes(script)) return { ok: false, reason: 'filtered out by --only' };
  if (skipArg && skipArg.split(',').includes(script)) return { ok: false, reason: 'filtered out by --skip' };
  const profile = STAGE_PROFILE[script];
  if (!profile) return { ok: false, reason: 'no profile' };
  if (profile.tier === 'external-service' && profile.envVar && !process.env[profile.envVar]) {
    return { ok: false, reason: 'env not set: ' + profile.envVar };
  }
  if (profile.tier === 'needs-app' && skipApp) {
    return { ok: false, reason: '--skip-app-server set' };
  }
  return { ok: true };
}

async function changedFiles() {
  if (!changedMode) return null;
  const base = process.env.QA_CHANGED_BASE || 'origin/main';
  return new Promise((resolve) => {
    const child = spawn('git', ['diff', '--name-only', base + '...HEAD']);
    let out = '';
    child.stdout.on('data', (d) => { out += d.toString(); });
    child.on('close', () => resolve(out.split('\\n').map((s) => s.trim()).filter(Boolean)));
    child.on('error', () => resolve([]));
  });
}

function touchedBy(script, changed) {
  const profile = STAGE_PROFILE[script];
  if (!profile?.touches?.length) return true;
  return changed.some((file) => profile.touches.some((prefix) => file.startsWith(prefix)));
}

function runScript(script, { timeoutMs = stageTimeoutMs } = {}) {
  return new Promise((resolve) => {
    const started = Date.now();
    process.stdout.write('\\n[qa:all] running ' + script + ' (' + (STAGE_PROFILE[script]?.tier || 'unknown') + ')\\n');
    const child = spawn('npm', ['run', script], {
      stdio: 'inherit',
      shell: process.platform === 'win32',
    });
    const timer = setTimeout(() => { try { child.kill('SIGKILL'); } catch {} }, timeoutMs);
    child.on('error', (error) => {
      clearTimeout(timer);
      record(script, 'error', { exitCode: -1, durationMs: Date.now() - started, reason: error.message });
      resolve(false);
    });
    child.on('close', (code) => {
      clearTimeout(timer);
      record(script, code === 0 ? 'passed' : 'failed', { exitCode: code, durationMs: Date.now() - started });
      resolve(code === 0);
    });
  });
}

async function waitForHealth(url, deadlineMs) {
  const deadline = Date.now() + deadlineMs;
  while (Date.now() < deadline) {
    try {
      const response = await fetch(url, { method: 'GET' });
      if (response.status < 500) return true;
    } catch {}
    await new Promise((r) => setTimeout(r, 1000));
  }
  return false;
}

function pickAppServerScript() {
  const override = process.env.QA_APP_SERVER;
  if (override && pkg.scripts?.[override]) return override;
  // Prefer 'dev' by default — it's a single command that doesn't require a prior build
  // step, which makes the orchestrator usable on a fresh clone. Set QA_APP_SERVER=start
  // (and ensure a production build exists) when you want production-mode behavior, e.g.
  // for representative perf runs.
  if (pkg.scripts?.dev) return 'dev';
  if (pkg.scripts?.start) return 'start';
  return null;
}

async function withAppServer(run) {
  if (process.env.QA_BASE_URL) {
    process.stdout.write('[qa:all] QA_BASE_URL set, skipping managed dev server\\n');
    return run();
  }
  const startScript = pickAppServerScript();
  if (!startScript) {
    record('app-server', 'skipped', { reason: 'no dev/start script' });
    return run();
  }
  const logPath = path.join(RESULTS_DIR, 'app-server.log');
  const log = createWriteStream(logPath, { flags: 'a' });
  process.stdout.write('[qa:all] starting app server (npm run ' + startScript + '), logs -> qa-results/app-server.log\\n');
  const child = spawn('npm', ['run', startScript], {
    stdio: ['ignore', 'pipe', 'pipe'],
    shell: process.platform === 'win32',
  });
  child.stdout.pipe(log);
  child.stderr.pipe(log);
  const cleanup = () => { try { child.kill('SIGTERM'); } catch {} };
  process.on('exit', cleanup);
  const healthy = await waitForHealth(baseUrl, healthTimeoutMs);
  if (!healthy) {
    record('app-server', 'failed', { reason: 'health probe timed out at ' + baseUrl + ' — see qa-results/app-server.log' });
    cleanup();
    return false;
  }
  try {
    return await run();
  } finally {
    cleanup();
  }
}

(async () => {
  const changed = await changedFiles();
  const selected = [];
  for (const script of ORDER) {
    const cls = classify(script);
    if (!cls.ok) { record(script, 'skipped', { reason: cls.reason }); continue; }
    if (changed && !touchedBy(script, changed)) { record(script, 'skipped', { reason: 'no changed files for stage' }); continue; }
    selected.push(script);
  }

  const zero = selected.filter((s) => STAGE_PROFILE[s].tier === 'zero-infra');
  const app = selected.filter((s) => STAGE_PROFILE[s].tier === 'needs-app');
  const external = selected.filter((s) => STAGE_PROFILE[s].tier === 'external-service');

  if (zero.length) {
    process.stdout.write('[qa:all] zero-infra: ' + zero.join(', ') + '\\n');
    await Promise.all(zero.map((script) => runScript(script)));
  }

  if (app.length) {
    process.stdout.write('[qa:all] needs-app: ' + app.join(', ') + '\\n');
    let ran = false;
    await withAppServer(async () => {
      ran = true;
      for (const script of app) await runScript(script);
      return true;
    });
    if (!ran) {
      for (const script of app) record(script, 'skipped', { reason: 'app server did not start — see qa-results/app-server.log' });
    }
  }

  if (external.length) {
    process.stdout.write('[qa:all] external-service: ' + external.join(', ') + '\\n');
    for (const script of external) await runScript(script);
  }

  // Severity gate: re-evaluate Trivy findings against --fail-on threshold.
  // Only applies when qa:security actually ran in this invocation.
  const trivyRecord = results.find((r) => r.script === 'qa:security');
  if (trivyRecord && trivyRecord.status !== 'skipped') {
    const trivyPath = path.join(RESULTS_DIR, 'trivy.json');
    try {
      const trivyReport = JSON.parse(readFileSync(trivyPath, 'utf8'));
      const vulns = (trivyReport.Results || []).flatMap((r) => r.Vulnerabilities || []);
      const counts = { low: 0, medium: 0, high: 0, critical: 0 };
      let overThreshold = 0;
      for (const v of vulns) {
        const sev = String(v.Severity || '').toLowerCase();
        if (sev in counts) counts[sev] += 1;
        if ((SEVERITY_RANK[sev] ?? -1) >= failThreshold) overThreshold += 1;
      }
      trivyRecord.severityCounts = counts;
      trivyRecord.overThreshold = overThreshold;
      trivyRecord.status = overThreshold ? 'failed' : 'passed';
      trivyRecord.reason = overThreshold ? 'matches at or above ' + failOn : undefined;
    } catch {}
  }

  if (pkg.scripts?.['qa:report']) {
    process.stdout.write('[qa:all] consolidating report\\n');
    await runScript('qa:report');
  }

  writeFileSync(path.join(RESULTS_DIR, 'qa-stages.json'), JSON.stringify({
    generatedAt: new Date().toISOString(),
    failOn,
    threshold: failThreshold,
    results,
  }, null, 2) + '\\n');

  const summary = {
    passed: results.filter((r) => r.status === 'passed').length,
    failed: results.filter((r) => r.status === 'failed' || r.status === 'error').length,
    skipped: results.filter((r) => r.status === 'skipped').length,
  };
  process.stdout.write('\\n[qa:all] summary: ' + JSON.stringify(summary) + '\\n');
  process.exit(summary.failed ? 1 : 0);
})();
`;
}

const QA_REPORT = `import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const outDir = path.join(root, 'qa-results');
mkdirSync(outDir, { recursive: true });

function readJson(rel) {
  const file = path.join(root, rel);
  if (!existsSync(file)) return null;
  try {
    return JSON.parse(readFileSync(file, 'utf8'));
  } catch (error) {
    return { parseError: error.message };
  }
}

function readJsonDir(rel) {
  const dir = path.join(root, rel);
  if (!existsSync(dir)) return [];
  try {
    return readdirSync(dir)
      .filter((name) => name.endsWith('.json'))
      .map((name) => readJson(path.join(rel, name)))
      .filter(Boolean);
  } catch {
    return [];
  }
}

function pct(value) {
  return Number.isFinite(value) ? Math.round(value * 100) / 100 : null;
}

function escapeXml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function row(cells) {
  return '<Row>' + cells.map((cell) => '<Cell><Data ss:Type="String">' + escapeXml(cell) + '</Data></Cell>').join('') + '</Row>';
}

function worksheet(name, rows) {
  return '<Worksheet ss:Name="' + escapeXml(name) + '"><Table>' + rows.join('') + '</Table></Worksheet>';
}

function summarizeLcov() {
  const file = path.join(root, 'coverage', 'lcov.info');
  if (!existsSync(file)) return null;
  const text = readFileSync(file, 'utf8');
  const found = { lines: 0, linesHit: 0, functions: 0, functionsHit: 0, branches: 0, branchesHit: 0 };
  for (const line of text.split(/\\r?\\n/)) {
    const [key, raw] = line.split(':');
    const value = Number(raw);
    if (key === 'LF') found.lines += value;
    if (key === 'LH') found.linesHit += value;
    if (key === 'FNF') found.functions += value;
    if (key === 'FNH') found.functionsHit += value;
    if (key === 'BRF') found.branches += value;
    if (key === 'BRH') found.branchesHit += value;
  }
  return {
    lines: pct(found.lines ? (found.linesHit / found.lines) * 100 : 0),
    functions: pct(found.functions ? (found.functionsHit / found.functions) * 100 : 0),
    branches: pct(found.branches ? (found.branchesHit / found.branches) * 100 : 0),
  };
}

function playwrightStatus(test) {
  const results = test.results || [];
  if (!results.length) return 'unknown';
  if (results.some((result) => result.status === 'failed' || result.status === 'timedOut')) return 'failed';
  if (results.every((result) => result.status === 'skipped')) return 'skipped';
  if (results.some((result) => result.status === 'passed')) return 'passed';
  return results.at(-1)?.status || 'unknown';
}

function describePlaywrightCase(title, file) {
  const normalized = title.toLowerCase();
  if (normalized.includes('smoke')) return 'Checks that the configured smoke page loads and renders page content.';
  if (normalized.includes('journey:')) return 'Checks a discovered user journey route renders and visible form controls can be safely exercised.';
  if (normalized.includes('critical journey')) return 'Checks the configured critical end-to-end journey page renders successfully.';
  return 'Checks Playwright browser behavior for ' + title + (file ? ' in ' + file : '') + '.';
}

function flattenPlaywrightSuite(suite, rows = [], parentTitles = []) {
  const suiteTitles = [...parentTitles, suite.title].filter(Boolean);
  for (const spec of suite.specs || []) {
    for (const test of spec.tests || []) {
      const results = test.results || [];
      const title = [...suiteTitles, spec.title].filter(Boolean).join(' > ');
      const status = playwrightStatus(test);
      const durationMs = results.reduce((sum, result) => sum + (result.duration || 0), 0);
      const errors = results
        .flatMap((result) => result.errors || [])
        .map((error) => error.message || error.value || '')
        .filter(Boolean)
        .join('\\n');
      rows.push({
        tool: 'playwright',
        suite: suiteTitles.join(' > '),
        file: spec.file || '',
        project: test.projectName || '',
        title,
        description: describePlaywrightCase(title, spec.file || ''),
        status,
        durationMs,
        retries: Math.max(0, results.length - 1),
        errors,
      });
    }
  }
  for (const child of suite.suites || []) flattenPlaywrightSuite(child, rows, suiteTitles);
  return rows;
}

function addPlaywright(report, rows, testCases) {
  if (!report) return;
  const allCases = (report.suites || []).flatMap((suite) => flattenPlaywrightSuite(suite));
  testCases.push(...allCases);
  // Visual tests get their own row; exclude here to avoid double-counting totals.
  const cases = allCases.filter((c) => !(/tests\\/visual\\//.test(c.file || '') || (c.title || '').includes('visual:')));
  const passed = cases.filter((test) => test.status === 'passed').length;
  const failed = cases.filter((test) => test.status === 'failed').length;
  const skipped = cases.filter((test) => test.status === 'skipped').length;
  rows.push({ tool: 'playwright', status: failed ? 'failed' : 'passed', total: cases.length, passed, failed, skipped, coverage: '', source: 'playwright-report/results.json' });
}

function addVitest(report, rows) {
  if (!report) return;
  const total = report.numTotalTests ?? report.totalTests ?? 0;
  const passed = report.numPassedTests ?? report.passedTests ?? 0;
  const failed = report.numFailedTests ?? report.failedTests ?? 0;
  const skipped = report.numPendingTests ?? report.numTodoTests ?? report.skippedTests ?? 0;
  rows.push({ tool: 'vitest', status: failed ? 'failed' : 'passed', total, passed, failed, skipped, coverage: '', source: 'qa-results/vitest.json' });
}

function addNewman(report, rows) {
  if (!report) return;
  const assertions = report.run?.stats?.assertions || {};
  rows.push({
    tool: 'postman',
    status: assertions.failed ? 'failed' : 'passed',
    total: assertions.total || 0,
    passed: (assertions.total || 0) - (assertions.failed || 0),
    failed: assertions.failed || 0,
    skipped: assertions.pending || 0,
    coverage: '',
    source: 'qa-results/newman.json',
  });
}

function flattenK6Groups(group, testCases, parentPath = '') {
  if (!group) return;
  const path = parentPath ? (group.name ? parentPath + ' > ' + group.name : parentPath) : group.name;
  
  if (group.checks) {
    for (const [checkName, checkData] of Object.entries(group.checks)) {
      testCases.push({
        tool: 'k6',
        file: 'tests/performance/load.js',
        title: path ? path + ' > ' + checkName : checkName,
        description: 'k6 performance check: ' + checkName,
        project: 'performance',
        status: checkData.fails > 0 ? 'failed' : 'passed',
        durationMs: 0,
        errors: checkData.fails > 0 ? checkData.fails + ' failures' : ''
      });
    }
  }
  
  if (group.groups) {
    for (const childGroup of Object.values(group.groups)) {
      flattenK6Groups(childGroup, testCases, path);
    }
  }
}

function addK6(report, rows, testCases) {
  if (!report) return;
  const metrics = report.metrics || {};
  const checks = metrics.checks || {};
  const passed = checks.passes || 0;
  const failed = checks.fails || 0;
  const requests = metrics.http_reqs?.count || 0;
  const p95 = metrics.http_req_duration?.['p(95)'];
  const failRate = metrics.http_req_failed?.value;
  const breaches = [];
  for (const [metricName, value] of Object.entries(metrics)) {
    const thresholds = value?.thresholds || {};
    for (const [name, crossed] of Object.entries(thresholds)) {
      if (crossed) breaches.push(metricName + ' ' + name);
    }
  }
  const summaryParts = [];
  if (requests) summaryParts.push('requests ' + requests);
  if (Number.isFinite(p95)) summaryParts.push('p95 ' + Math.round(p95) + 'ms');
  if (Number.isFinite(failRate)) summaryParts.push('fail_rate ' + (failRate * 100).toFixed(2) + '%');
  const item = {
    tool: 'k6',
    status: breaches.length ? 'failed' : 'passed',
    total: passed + failed,
    passed,
    failed,
    skipped: 0,
    coverage: summaryParts.join(', '),
    source: 'qa-results/k6-summary.json',
  };
  if (breaches.length) item.breaches = breaches;
  rows.push(item);

  if (report.root_group && testCases) {
    flattenK6Groups(report.root_group, testCases);
  }
}

function addVisual(playwrightReport, rows) {
  if (!playwrightReport) return;
  const cases = (playwrightReport.suites || []).flatMap((suite) => flattenPlaywrightSuite(suite));
  const visual = cases.filter((c) => /tests\\/visual\\//.test(c.file || '') || (c.title || '').includes('visual:'));
  if (!visual.length) return;
  const passed = visual.filter((c) => c.status === 'passed').length;
  const failed = visual.filter((c) => c.status === 'failed').length;
  const skipped = visual.filter((c) => c.status === 'skipped').length;
  rows.push({
    tool: 'visual',
    status: failed ? 'failed' : 'passed',
    total: visual.length,
    passed,
    failed,
    skipped,
    coverage: failed ? failed + ' diff(s)' : '',
    source: 'playwright-report/results.json (tests/visual)',
  });
}

function addAxe(reports, rows) {
  if (!reports.length) return;
  const violations = reports.flatMap((r) => (r.violations || []).map((v) => ({ ...v, route: r.path })));
  const total = violations.length;
  const counts = { minor: 0, moderate: 0, serious: 0, critical: 0 };
  for (const v of violations) {
    const impact = String(v.impact || 'minor').toLowerCase();
    if (impact in counts) counts[impact] += 1;
  }
  const blocking = counts.serious + counts.critical;
  const coverageParts = [];
  if (counts.critical) coverageParts.push('critical ' + counts.critical);
  if (counts.serious) coverageParts.push('serious ' + counts.serious);
  if (counts.moderate) coverageParts.push('moderate ' + counts.moderate);
  if (counts.minor) coverageParts.push('minor ' + counts.minor);
  rows.push({
    tool: 'axe',
    status: blocking ? 'failed' : 'passed',
    total,
    passed: 0,
    failed: blocking,
    skipped: total - blocking,
    coverage: coverageParts.join(', '),
    source: 'qa-results/axe/*.json',
  });
}

function addGitleaks(report, rows) {
  if (!report) return;
  const leaks = Array.isArray(report) ? report : (report.findings || []);
  const total = leaks.length;
  rows.push({
    tool: 'gitleaks',
    status: total ? 'failed' : 'passed',
    total,
    passed: 0,
    failed: total,
    skipped: 0,
    coverage: total ? total + ' secret finding(s)' : '',
    source: 'qa-results/gitleaks.json',
  });
}

function addSemgrep(report, rows) {
  if (!report) return;
  const results = report.results || [];
  const counts = { error: 0, warning: 0, info: 0 };
  for (const r of results) {
    const sev = String(r.extra?.severity || '').toLowerCase();
    if (sev in counts) counts[sev] += 1;
  }
  const blocking = counts.error + counts.warning;
  const coverageParts = [];
  if (counts.error) coverageParts.push('error ' + counts.error);
  if (counts.warning) coverageParts.push('warning ' + counts.warning);
  if (counts.info) coverageParts.push('info ' + counts.info);
  rows.push({
    tool: 'semgrep',
    status: blocking ? 'failed' : 'passed',
    total: results.length,
    passed: 0,
    failed: blocking,
    skipped: results.length - blocking,
    coverage: coverageParts.join(', '),
    source: 'qa-results/semgrep.json',
  });
}

function addTrivy(report, rows) {
  if (!report) return;
  const vulns = (report.Results || []).flatMap((r) => r.Vulnerabilities || []);
  const total = vulns.length;
  const counts = { low: 0, medium: 0, high: 0, critical: 0 };
  for (const v of vulns) {
    const sev = String(v.Severity || '').toLowerCase();
    if (sev in counts) counts[sev] += 1;
  }
  const coverageParts = [];
  if (counts.critical) coverageParts.push('critical ' + counts.critical);
  if (counts.high) coverageParts.push('high ' + counts.high);
  if (counts.medium) coverageParts.push('medium ' + counts.medium);
  if (counts.low) coverageParts.push('low ' + counts.low);
  rows.push({
    tool: 'trivy',
    status: total ? 'failed' : 'passed',
    total,
    passed: 0,
    failed: total,
    skipped: 0,
    coverage: coverageParts.join(', '),
    source: 'qa-results/trivy.json',
  });
}

const STATUS_LABEL = { passed: 'Pass', failed: 'Fail', skipped: 'Skipped' };
const SEVERITY_PRIORITY = { critical: 'Critical', high: 'High', medium: 'Medium', low: 'Low', negligible: 'Low', unknown: 'Medium' };
const SEVERITY_RANK = { negligible: 0, low: 0, medium: 1, high: 2, critical: 3, unknown: 1 };
const qaCases = [];
const counters = {};
function nextId(prefix) { counters[prefix] = (counters[prefix] || 0) + 1; return prefix + '-' + String(counters[prefix]).padStart(3, '0'); }

function playwrightType(file) {
  if (!file) return { type: 'E2E', priority: 'High' };
  if (file.includes('tests/smoke/')) return { type: 'Smoke', priority: 'High' };
  if (file.includes('tests/e2e/user-journeys')) return { type: 'User Journey', priority: 'Medium' };
  if (file.includes('tests/e2e/')) return { type: 'E2E', priority: 'High' };
  return { type: 'E2E', priority: 'Medium' };
}

function pageFromPlaywright(testCase) {
  const m = (testCase.title || '').match(/journey:\\s*(.+)$/i);
  if (m) return m[1].trim();
  if ((testCase.title || '').toLowerCase().includes('smoke')) return 'Smoke target';
  return testCase.file || testCase.suite || 'Unknown';
}

function buildPlaywrightQaCases(testCases) {
  for (const tc of testCases) {
    // Visual tests are surfaced as QA-VIS cases; skip them here to avoid
    // double-counting in the QA Test Cases sheet.
    if (/tests\\/visual\\//.test(tc.file || '') || (tc.title || '').includes('visual:')) continue;
    const { type, priority } = playwrightType(tc.file);
    qaCases.push({
      testCaseId: nextId('QA-PW'),
      pageName: pageFromPlaywright(tc),
      summary: tc.title,
      priority,
      prerequisites: 'App reachable at QA_BASE_URL (default http://localhost:3000)',
      testType: type,
      testSteps: tc.description || 'Run Playwright spec ' + (tc.file || ''),
      testData: 'Project: ' + (tc.project || 'chromium'),
      expectedResult: type === 'User Journey'
        ? 'Route renders and visible form controls can be exercised without error'
        : 'Page renders successfully and returns expected status',
      actualResult: tc.status === 'passed'
        ? 'Passed in ' + tc.durationMs + 'ms'
        : (tc.errors || 'Status: ' + tc.status),
      status: STATUS_LABEL[tc.status] || 'Unknown',
    });
  }
}

function buildVitestQaCases(report) {
  if (!report) return;
  for (const suite of report.testResults || []) {
    const file = (suite.name || '').replace(root + '/', '').replace(root, '');
    for (const assertion of suite.assertionResults || []) {
      const passed = assertion.status === 'passed';
      qaCases.push({
        testCaseId: nextId('QA-UNIT'),
        pageName: file || 'Unit suite',
        summary: assertion.fullName || assertion.title,
        priority: 'Medium',
        prerequisites: '',
        testType: 'Unit',
        testSteps: 'Run Vitest unit assertion: ' + (assertion.title || assertion.fullName),
        testData: '',
        expectedResult: 'Assertion passes',
        actualResult: passed
          ? 'Passed'
          : (assertion.failureMessages || []).join('\\n').slice(0, 500) || 'Status: ' + assertion.status,
        status: STATUS_LABEL[assertion.status] || (passed ? 'Pass' : 'Fail'),
      });
    }
  }
}

function formatNewmanUrl(url) {
  if (!url) return '';
  if (typeof url === 'string') return url;
  if (typeof url.raw === 'string' && url.raw.length) return url.raw;
  const host = Array.isArray(url.host) ? url.host.join('.') : (url.host || '');
  const pathParts = Array.isArray(url.path) ? url.path.join('/') : (url.path || '');
  const port = url.port ? ':' + url.port : '';
  const proto = url.protocol ? url.protocol + '://' : '';
  const path = pathParts ? '/' + pathParts.replace(/^\\/+/, '') : '';
  return proto + host + port + path;
}

function buildNewmanQaCases(report) {
  if (!report) return;
  const executions = report.run?.executions || [];
  for (const exec of executions) {
    const method = exec.item?.request?.method || exec.request?.method || 'GET';
    const url = formatNewmanUrl(exec.request?.url) || formatNewmanUrl(exec.item?.request?.url);
    const itemName = exec.item?.name || (method + ' ' + url);
    const target = url || itemName;
    for (const assertion of exec.assertions || []) {
      const failed = Boolean(assertion.error);
      qaCases.push({
        testCaseId: nextId('QA-API'),
        pageName: target,
        summary: assertion.assertion || itemName,
        priority: 'High',
        prerequisites: 'API reachable at {{baseUrl}} (postman/qa-env.json)',
        testType: 'API',
        testSteps: 'Send ' + method + ' ' + target + ' and assert: ' + (assertion.assertion || ''),
        testData: 'Collection: postman/qa-collection.json; Env: postman/qa-env.json',
        expectedResult: assertion.assertion || 'Assertion holds',
        actualResult: failed ? (assertion.error?.message || 'Failed') : 'Passed',
        status: failed ? 'Fail' : 'Pass',
      });
    }
  }
}

function buildK6QaCases(report) {
  if (!report) return;
  const metrics = report.metrics || {};
  for (const [metricName, value] of Object.entries(metrics)) {
    const thresholds = value?.thresholds || {};
    for (const [expr, crossed] of Object.entries(thresholds)) {
      let observed = '';
      if (metricName === 'http_req_duration' && Number.isFinite(value['p(95)'])) observed = 'p95=' + Math.round(value['p(95)']) + 'ms';
      else if (metricName === 'http_req_failed' && Number.isFinite(value.value)) observed = 'rate=' + (value.value * 100).toFixed(2) + '%';
      else if (metricName === 'checks' && Number.isFinite(value.value)) observed = 'rate=' + (value.value * 100).toFixed(2) + '%';
      qaCases.push({
        testCaseId: nextId('QA-PERF'),
        pageName: 'Load profile (all discovered endpoints)',
        summary: metricName + ' ' + expr,
        priority: 'High',
        prerequisites: 'API reachable at QA_K6_BASE_URL or QA_BASE_URL',
        testType: 'Performance',
        testSteps: 'Run k6 load test (VUs=$QA_K6_VUS||5, duration=$QA_K6_DURATION||30s) and check ' + metricName + ' ' + expr,
        testData: 'tests/performance/load.js',
        expectedResult: 'Threshold ' + expr + ' holds',
        actualResult: (crossed ? 'Threshold crossed' : 'Threshold held') + (observed ? ' (' + observed + ')' : ''),
        status: crossed ? 'Fail' : 'Pass',
      });
    }
  }
}

function buildVisualQaCases(playwrightReport) {
  if (!playwrightReport) return;
  const cases = (playwrightReport.suites || []).flatMap((suite) => flattenPlaywrightSuite(suite));
  const visual = cases.filter((c) => /tests\\/visual\\//.test(c.file || '') || (c.title || '').includes('visual:'));
  for (const c of visual) {
    const failed = c.status === 'failed';
    qaCases.push({
      testCaseId: nextId('QA-VIS'),
      pageName: c.title.replace(/^.*?visual:\\s*/, ''),
      summary: c.title,
      priority: failed ? 'High' : 'Medium',
      prerequisites: 'App reachable at QA_BASE_URL; baseline images committed',
      testType: 'Visual',
      testSteps: 'Navigate to route, take full-page screenshot, compare to baseline',
      testData: 'maxDiffPixels=' + (process.env.QA_VISUAL_MAX_DIFF_PIXELS || 100) + '; maxDiffPixelRatio=' + (process.env.QA_VISUAL_MAX_DIFF_RATIO || 0.01),
      expectedResult: 'Screenshot matches baseline within configured tolerance',
      actualResult: failed ? (c.errors || 'Diff exceeded tolerance') : 'Matches baseline (' + c.durationMs + 'ms)',
      status: failed ? 'Fail' : (c.status === 'skipped' ? 'Skipped' : 'Pass'),
    });
  }
}

function buildAxeQaCases(reports) {
  if (!reports.length) return;
  const PRIORITY = { critical: 'Critical', serious: 'High', moderate: 'Medium', minor: 'Low' };
  for (const r of reports) {
    for (const v of r.violations || []) {
      const impact = String(v.impact || 'minor').toLowerCase();
      const blocking = impact === 'serious' || impact === 'critical';
      qaCases.push({
        testCaseId: nextId('QA-A11Y'),
        pageName: r.path || 'unknown',
        summary: v.id || 'a11y violation',
        priority: PRIORITY[impact] || 'Medium',
        prerequisites: 'App reachable at QA_BASE_URL; @axe-core/playwright installed',
        testType: 'Accessibility',
        testSteps: 'Run axe-core on ' + (r.path || 'route') + ' and check rule ' + (v.id || ''),
        testData: 'Impact: ' + impact + (v.tags?.length ? '; tags: ' + v.tags.slice(0, 3).join(',') : ''),
        expectedResult: v.help || 'No violations of rule ' + (v.id || ''),
        actualResult: (v.nodes?.length || 0) + ' element(s) affected' + (v.helpUrl ? ' — ' + v.helpUrl : ''),
        status: blocking ? 'Fail' : 'Pass',
      });
    }
  }
}

function buildGitleaksQaCases(report) {
  if (!report) return;
  const leaks = Array.isArray(report) ? report : (report.findings || []);
  for (const leak of leaks) {
    qaCases.push({
      testCaseId: nextId('QA-LEAK'),
      pageName: (leak.File || 'unknown') + (leak.StartLine ? ':' + leak.StartLine : ''),
      summary: leak.RuleID || leak.Description || 'secret detected',
      priority: 'High',
      prerequisites: '',
      testType: 'Secrets',
      testSteps: 'Run gitleaks against the repository working tree',
      testData: '.gitleaks.toml; ruleID: ' + (leak.RuleID || ''),
      expectedResult: 'No committed or staged secrets in the working tree',
      actualResult: String(leak.Match || leak.Secret || 'redacted match').slice(0, 200),
      status: 'Fail',
    });
  }
}

function buildSemgrepQaCases(report) {
  if (!report) return;
  const PRIORITY = { error: 'High', warning: 'Medium', info: 'Low' };
  for (const r of report.results || []) {
    const sev = String(r.extra?.severity || 'info').toLowerCase();
    const blocking = sev === 'error' || sev === 'warning';
    const location = (r.path || 'unknown') + (r.start?.line ? ':' + r.start.line : '');
    qaCases.push({
      testCaseId: nextId('QA-SAST'),
      pageName: location,
      summary: r.check_id || 'semgrep finding',
      priority: PRIORITY[sev] || 'Medium',
      prerequisites: '',
      testType: 'SAST',
      testSteps: 'Run Semgrep with the auto config against the repository',
      testData: 'severity: ' + sev,
      expectedResult: 'No findings at or above warning severity',
      actualResult: String(r.extra?.message || r.check_id || '').slice(0, 200),
      status: blocking ? 'Fail' : 'Pass',
    });
  }
}

function buildTrivyQaCases(report, threshold) {
  if (!report) return;
  for (const result of report.Results || []) {
    for (const v of result.Vulnerabilities || []) {
      const sev = String(v.Severity || 'unknown').toLowerCase();
      const rank = SEVERITY_RANK[sev] ?? SEVERITY_RANK.unknown;
      const blocking = rank >= threshold;
      qaCases.push({
        testCaseId: nextId('QA-SEC'),
        pageName: (v.PkgName || 'package') + '@' + (v.InstalledVersion || ''),
        summary: v.VulnerabilityID || 'Vulnerability',
        priority: SEVERITY_PRIORITY[sev] || 'Medium',
        prerequisites: '',
        testType: 'Security',
        testSteps: 'Scan with Trivy fs against severity threshold (target: ' + (result.Target || '') + ')',
        testData: '.trivyignore; severity: ' + sev,
        expectedResult: 'No vulnerabilities at or above configured severity threshold',
        actualResult: (v.VulnerabilityID || 'finding') + ' (' + sev + ')' + (v.Title ? ': ' + String(v.Title).slice(0, 200) : ''),
        status: blocking ? 'Fail' : 'Pass',
      });
    }
  }
}

// Each Playwright stage writes its own JSON via PLAYWRIGHT_JSON_OUTPUT_FILE so
// they don't clobber each other. Merge them all here before parsing.
function mergePlaywrightReports() {
  const reports = readJsonDir('playwright-report');
  const legacy = readJson('playwright-report/results.json');
  const all = legacy ? [legacy, ...reports.filter((r) => r !== legacy)] : reports;
  const merged = { suites: [] };
  const seenSuiteFiles = new Set();
  for (const r of all) {
    for (const suite of r?.suites || []) {
      // Dedupe by suite identifier where possible (file + title) so the legacy
      // results.json doesn't double-count anything also written per-stage.
      const key = (suite.file || '') + '::' + (suite.title || '');
      if (seenSuiteFiles.has(key)) continue;
      seenSuiteFiles.add(key);
      merged.suites.push(suite);
    }
  }
  return merged.suites.length ? merged : null;
}

const rows = [];
const testCases = [];
const mergedPlaywright = mergePlaywrightReports();
addPlaywright(mergedPlaywright, rows, testCases);
addVitest(readJson('qa-results/vitest.json'), rows);
addNewman(readJson('qa-results/newman.json'), rows);
addK6(readJson('qa-results/k6-summary.json'), rows, testCases);
addVisual(mergedPlaywright, rows);
addAxe(readJsonDir('qa-results/axe'), rows);
addGitleaks(readJson('qa-results/gitleaks.json'), rows);
addSemgrep(readJson('qa-results/semgrep.json'), rows);
addTrivy(readJson('qa-results/trivy.json'), rows);

const stages = readJson('qa-results/qa-stages.json');
const failOn = (stages?.failOn || process.env.QA_FAIL_ON || 'high').toLowerCase();
const grypeThreshold = SEVERITY_RANK[failOn] ?? SEVERITY_RANK.high;
buildPlaywrightQaCases(testCases);
buildVitestQaCases(readJson('qa-results/vitest.json'));
buildNewmanQaCases(readJson('qa-results/newman.json'));
buildK6QaCases(readJson('qa-results/k6-summary.json'));
buildVisualQaCases(mergedPlaywright);
buildAxeQaCases(readJsonDir('qa-results/axe'));
buildGitleaksQaCases(readJson('qa-results/gitleaks.json'));
buildSemgrepQaCases(readJson('qa-results/semgrep.json'));
buildTrivyQaCases(readJson('qa-results/trivy.json'), grypeThreshold);

const lcov = summarizeLcov();
if (lcov) {
  rows.push({ tool: 'coverage', status: 'reported', total: '', passed: '', failed: '', skipped: '', coverage: 'lines ' + lcov.lines + '%, functions ' + lcov.functions + '%, branches ' + lcov.branches + '%', source: 'coverage/lcov.info' });
}

const summary = rows.reduce((acc, item) => {
  acc.total += Number(item.total) || 0;
  acc.passed += Number(item.passed) || 0;
  acc.failed += Number(item.failed) || 0;
  acc.skipped += Number(item.skipped) || 0;
  if (item.status === 'failed') acc.status = 'failed';
  return acc;
}, { status: 'passed', total: 0, passed: 0, failed: 0, skipped: 0 });

const report = { generatedAt: new Date().toISOString(), summary, rows, testCases, qaTestCases: qaCases };
writeFileSync(path.join(outDir, 'qa-report.json'), JSON.stringify(report, null, 2) + '\\n');

const workbook = '<?xml version="1.0"?>\\n<?mso-application progid="Excel.Sheet"?>\\n<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">' +
  worksheet('Summary', [
    row(['Metric', 'Value']),
    row(['Status', summary.status]),
    row(['Total checks', summary.total]),
    row(['Passed', summary.passed]),
    row(['Failed', summary.failed]),
    row(['Skipped', summary.skipped]),
    row(['Generated at', report.generatedAt]),
  ]) +
  worksheet('Tools', [
    row(['Tool', 'Status', 'Total', 'Passed', 'Failed', 'Skipped', 'Coverage', 'Source']),
    ...rows.map((item) => row([item.tool, item.status, item.total, item.passed, item.failed, item.skipped, item.coverage, item.source])),
  ]) +
  worksheet('Test Cases', [
    row(['Tool', 'Suite', 'File', 'Project', 'Test Case', 'Description', 'Status', 'Duration ms', 'Retries', 'Errors']),
    ...testCases.map((item) => row([item.tool, item.suite, item.file, item.project, item.title, item.description, item.status, item.durationMs, item.retries, item.errors])),
  ]) +
  worksheet('QA Test Cases', [
    row(['Test Case Id', 'Page Name', 'Summary', 'Priority', 'Prerequisites', 'Test Type', 'Test Steps', 'Test Data / Condition', 'Expected Result', 'Actual Result', 'Status']),
    ...qaCases.map((item) => row([item.testCaseId, item.pageName, item.summary, item.priority, item.prerequisites, item.testType, item.testSteps, item.testData, item.expectedResult, item.actualResult, item.status])),
  ]) +
  '</Workbook>\\n';
writeFileSync(path.join(outDir, 'qa-report.xls'), workbook);

console.log(JSON.stringify({ output: ['qa-results/qa-report.json', 'qa-results/qa-report.xls'], summary }, null, 2));
`;

function hasScript(pkg, name) {
  return Boolean(pkg?.scripts?.[name]);
}

function addScript(scripts, name, command) {
  if (!scripts[name]) scripts[name] = command;
}

// Upgrade an agent-managed script: if the existing value is one of the known
// prior versions (or missing), replace with the new command. Preserves any
// user-customized command (where the existing value doesn't match a known
// prior version we shipped).
function upgradeScript(scripts, name, newCmd, knownPriorCmds = []) {
  if (!scripts[name] || knownPriorCmds.includes(scripts[name])) {
    scripts[name] = newCmd;
  }
}

function addDevDependency(devDependencies, name, version) {
  if (!devDependencies[name]) devDependencies[name] = version;
}

export function generateAssets(scan, plan, options = {}) {
  const pkg = scan.packageJson ? structuredClone(scan.packageJson) : { scripts: {} };
  pkg.scripts = pkg.scripts || {};
  pkg.devDependencies = pkg.devDependencies || {};

  const enabled = new Set(plan.enabledTools || []);
  const enrichment = options.enrichment instanceof Map ? options.enrichment : new Map();
  const journeysOverride = Array.isArray(options.journeys) ? options.journeys : null;
  const files = [];
  const deps = pkg.devDependencies;
  const qaOrder = plan.recommendedOrder.filter((script) => script !== "qa:all" && script !== "qa:report");

  addScript(pkg.scripts, "qa:prepare", "node -e \"require('fs').mkdirSync('qa-results',{recursive:true})\"");

  if (enabled.has("playwright")) {
    const journeys = journeysOverride || discoverUserJourneys(scan.files);
    upgradeScript(pkg.scripts, "qa:smoke",
      "PLAYWRIGHT_JSON_OUTPUT_FILE=playwright-report/smoke.json playwright test tests/smoke",
      ["playwright test tests/smoke"]);
    upgradeScript(pkg.scripts, "qa:e2e",
      "PLAYWRIGHT_JSON_OUTPUT_FILE=playwright-report/e2e.json playwright test tests/e2e/critical-journey.spec.ts",
      ["playwright test tests/e2e"]);
    upgradeScript(pkg.scripts, "qa:journeys",
      "PLAYWRIGHT_JSON_OUTPUT_FILE=playwright-report/journeys.json playwright test tests/e2e/user-journeys.spec.ts",
      ["playwright test tests/e2e/user-journeys.spec.ts"]);
    addDevDependency(deps, "@playwright/test", "^1.56.1");
    if (!scan.facts.hasPlaywrightConfig) files.push({ path: "playwright.config.ts", content: PLAYWRIGHT_CONFIG });
    files.push({ path: "tests/smoke/qa-smoke.spec.ts", content: PLAYWRIGHT_SMOKE });
    files.push({ path: "tests/e2e/critical-journey.spec.ts", content: PLAYWRIGHT_E2E });
    files.push({ path: "tests/e2e/user-journeys.spec.ts", content: createPlaywrightJourneySpec(journeys, enrichment) });
  }

  if (enabled.has("vitest")) {
    const newQaUnit = "npm run qa:prepare && vitest run tests/unit --coverage --reporter=json --outputFile=qa-results/vitest.json";
    const knownPriorQaUnit = "npm run qa:prepare && vitest run --coverage --reporter=json --outputFile=qa-results/vitest.json";
    if (!pkg.scripts["qa:unit"] || pkg.scripts["qa:unit"] === knownPriorQaUnit) {
      pkg.scripts["qa:unit"] = newQaUnit;
    }
    addDevDependency(deps, "vitest", "^4.1.5");
    addDevDependency(deps, "@vitest/coverage-v8", "^4.1.5");
    files.push({ path: "tests/unit/qa-baseline.test.js", content: VITEST });
    files.push({ path: "tests/unit/qa-generated-regression.test.js", content: createGeneratedUnitTests(discoverUnitTestTargets(scan)) });
  }

  if (enabled.has("sonarqube")) {
    addScript(pkg.scripts, "qa:quality", "echo \\\"Quality checks are now handled by Trivy!\\\"");
  }

  if (enabled.has("postman") || enabled.has("k6")) {
    const endpoints = discoverApiEndpoints(scan.files, { repoRoot: scan.root });
    if (enabled.has("postman")) {
      addScript(pkg.scripts, "qa:api", "npm run qa:prepare && newman run postman/qa-collection.json -e postman/qa-env.json --reporters cli,json --reporter-json-export qa-results/newman.json");
      addDevDependency(deps, "newman", "^6.2.1");
      files.push({ path: "postman/qa-collection.json", content: createPostmanCollection(endpoints) });
      files.push({ path: "postman/qa-env.json", content: createPostmanEnv(endpoints) });
    }
    if (enabled.has("k6")) {
      addScript(pkg.scripts, "qa:perf", "npm run qa:prepare && k6 run --summary-export qa-results/k6-summary.json tests/performance/load.js");
      files.push({ path: "tests/performance/load.js", content: createK6Script(endpoints) });
    }
  }

  if (enabled.has("axe") && enabled.has("playwright")) {
    const journeys = journeysOverride || discoverUserJourneys(scan.files);
    upgradeScript(pkg.scripts, "qa:a11y",
      "PLAYWRIGHT_JSON_OUTPUT_FILE=playwright-report/a11y.json playwright test tests/a11y/qa-a11y.spec.ts",
      ["playwright test tests/a11y/qa-a11y.spec.ts"]);
    addDevDependency(deps, "@axe-core/playwright", "^4.10.1");
    addDevDependency(deps, "axe-core", "^4.10.2");
    files.push({ path: "tests/a11y/qa-a11y.spec.ts", content: createAxeSpec(journeys) });
  }

  if (enabled.has("visual") && enabled.has("playwright")) {
    const journeys = journeysOverride || discoverUserJourneys(scan.files);
    upgradeScript(pkg.scripts, "qa:visual",
      "PLAYWRIGHT_JSON_OUTPUT_FILE=playwright-report/visual.json playwright test tests/visual/qa-visual.spec.ts",
      ["playwright test tests/visual/qa-visual.spec.ts"]);
    upgradeScript(pkg.scripts, "qa:visual:update",
      "PLAYWRIGHT_JSON_OUTPUT_FILE=playwright-report/visual.json playwright test tests/visual/qa-visual.spec.ts --update-snapshots",
      ["playwright test tests/visual/qa-visual.spec.ts --update-snapshots"]);
    files.push({ path: "tests/visual/qa-visual.spec.ts", content: createVisualSpec(journeys) });
  }

  if (enabled.has("gitleaks")) {
    addScript(pkg.scripts, "qa:secrets", "npm run qa:prepare && gitleaks detect --report-format json --report-path qa-results/gitleaks.json --no-git --no-banner --exit-code 0");
    files.push({ path: ".gitleaks.toml", content: GITLEAKS_CONFIG });
  }

  if (enabled.has("semgrep")) {
    addScript(pkg.scripts, "qa:sast", "npm run qa:prepare && semgrep --config auto --json --output qa-results/semgrep.json --quiet .");
  }

  if (enabled.has("trivy")) {
    const newQaSec = "npm run qa:prepare && trivy fs --format json --output qa-results/trivy.json --quiet .";
    pkg.scripts["qa:security"] = newQaSec;
    files.push({ path: ".trivyignore", content: createTrivyIgnore(scan) });
  }

  addScript(pkg.scripts, "qa:report", "node scripts/qa-report.mjs");
  if (qaOrder.some((script) => pkg.scripts[script])) addScript(pkg.scripts, "qa:all", "node scripts/qa-run-all.mjs");

  files.push({ path: "scripts/qa-run-all.mjs", content: createQaRunAll(qaOrder) });
  files.push({ path: "scripts/qa-report.mjs", content: QA_REPORT });

  return {
    packageJson: `${JSON.stringify(pkg, null, 2)}\n`,
    files,
  };
}
