export function discoverSecurityTargets(scan) {
  const files = scan.files || [];
  const manifests = files.filter((file) => [
    "package.json",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
  ].includes(file) || /^Dockerfile/.test(file)).sort();
  const envExamples = files.filter((file) => /^\.env\.example$|(^|\/)\.env\.example$|(^|\/)env\.example$/.test(file)).sort();

  return {
    manifests,
    envExamples,
    hasContainer: scan.facts?.hasDockerfile || manifests.some((file) => /^Dockerfile/.test(file)),
    hasNodeLockfile: manifests.some((file) => ["package-lock.json", "pnpm-lock.yaml", "yarn.lock"].includes(file)),
  };
}

export function createGrypeConfig(scan) {
  const targets = discoverSecurityTargets(scan);
  return [
    "# Generated by repo-aware-testing-agent.",
    "# Grype scans dependency manifests and container files for known vulnerabilities.",
    "check-for-app-update: false",
    "output: json",
    "quiet: true",
    "scope: all-layers",
    "",
    "# CI can override the fail threshold with: grype . --fail-on critical",
    "# Current generated QA script fails on high and critical vulnerabilities.",
    "",
    `# Detected manifests: ${targets.manifests.join(", ") || "none"}`,
    `# Detected env examples: ${targets.envExamples.join(", ") || "none"}`,
    "",
  ].join("\n");
}
