export function discoverSecurityTargets(scan) {
  const files = scan.files || [];
  const manifests = files.filter((file) => [
    "package.json",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    "Cargo.toml",
    "Cargo.lock",
    "go.mod",
    "go.sum",
    "pyproject.toml",
    "Pipfile",
    "Pipfile.lock",
    "requirements.txt",
    "pom.xml",
    "build.gradle",
    "build.gradle.kts",
  ].includes(file) || /^Dockerfile/.test(file) || /^requirements.*\.txt$/.test(file)).sort();
  const envExamples = files.filter((file) => /^\.env\.example$|(^|\/)\.env\.example$|(^|\/)env\.example$/.test(file)).sort();

  return {
    manifests,
    envExamples,
    hasContainer: scan.facts?.hasDockerfile || manifests.some((file) => /^Dockerfile/.test(file)),
    hasNodeLockfile: manifests.some((file) => ["package-lock.json", "pnpm-lock.yaml", "yarn.lock"].includes(file)),
  };
}

export function createTrivyIgnore(scan) {
  const targets = discoverSecurityTargets(scan);
  return [
    "# Generated by repo-aware-testing-agent.",
    "# Trivy scans dependency manifests, container files, IaC, and secrets.",
    "# qa:security runs: trivy fs --format json --output qa-results/trivy.json .",
    "# Severity gating is applied by scripts/qa-run-all.mjs via --fail-on.",
    "#",
    "# Use this file to suppress known/accepted findings. One CVE ID per line:",
    "#   CVE-2023-12345",
    "#   GHSA-xxxx-yyyy-zzzz",
    "# Optionally scope by expiration:  CVE-2023-12345 exp:2026-12-31",
    "#",
    `# Detected manifests: ${targets.manifests.join(", ") || "none"}`,
    `# Detected env examples: ${targets.envExamples.join(", ") || "none"}`,
    "",
  ].join("\n");
}
