/**
 * Convert imported API rows (from the APIs sheet of a stories workbook)
 * into a Postman v2.1 collection. Output is structurally compatible with
 * what `harImport.js` produces, so the agent's existing Postman pipeline
 * (qa:api / newman) consumes it unchanged.
 *
 * Each row gets:
 *   - One Postman item with method + URL parsed against `{{apiHost}}`
 *   - A response-status assertion (uses row.statusCode or defaults by method)
 *   - A JSON-shape assertion when the row content-type implies JSON
 *   - A body when the row's request payload parses as JSON
 */

const DEFAULT_STATUS_BY_METHOD = {
  GET: 200,
  POST: 201,
  PUT: 200,
  PATCH: 200,
  DELETE: 204,
  HEAD: 200,
  OPTIONS: 204,
};

function tryParseJson(raw) {
  if (!raw) return null;
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function splitUrl(rawPath) {
  // Returns { host, pathSegments, host_var } where host is "{{apiHost}}"
  // for relative paths and the literal origin for absolute ones.
  if (/^https?:\/\//.test(rawPath)) {
    try {
      const u = new URL(rawPath);
      return {
        host: [u.host],
        protocol: u.protocol.replace(":", ""),
        path: u.pathname.replace(/^\//, "").split("/").filter(Boolean),
      };
    } catch {
      // fall through
    }
  }
  const trimmed = rawPath.replace(/^\/+/, "");
  return {
    host: ["{{apiHost}}"],
    protocol: null,
    path: trimmed.split("/").filter(Boolean),
  };
}

function buildAssertions(api) {
  const expected = Number(api.statusCode) || DEFAULT_STATUS_BY_METHOD[api.method] || 200;
  const lines = [`pm.test('status ${expected}', () => pm.response.to.have.status(${expected}));`];
  const ct = (api.contentType || "").toLowerCase();
  const looksJson = !ct || ct.includes("application/json");
  if (looksJson) {
    lines.push(`pm.test('returns JSON', () => { pm.response.json(); });`);
  }
  const expectedShape = tryParseJson(api.response);
  if (expectedShape && typeof expectedShape === "object" && !Array.isArray(expectedShape)) {
    for (const key of Object.keys(expectedShape).slice(0, 6)) {
      lines.push(
        `pm.test('response has ${key}', () => pm.expect(pm.response.json()).to.have.property('${key.replace(/'/g, "\\'")}'));`
      );
    }
  }
  return lines;
}

function buildRequestBody(api) {
  if (!api.request) return null;
  const parsed = tryParseJson(api.request);
  if (parsed !== null) {
    return {
      mode: "raw",
      raw: JSON.stringify(parsed, null, 2),
      options: { raw: { language: "json" } },
    };
  }
  return { mode: "raw", raw: String(api.request) };
}

export function apiToPostmanItem(api) {
  if (!api?.path || !api?.method) return null;
  const url = splitUrl(api.path);
  const headers = [];
  if (api.contentType) headers.push({ key: "Content-Type", value: api.contentType });
  else if (["POST", "PUT", "PATCH"].includes(api.method) && api.request) headers.push({ key: "Content-Type", value: "application/json" });
  if (String(api.auth || "").trim() && api.auth !== "false")
    headers.push({ key: "Authorization", value: "Bearer {{authToken}}" });

  const item = {
    name: `${api.method} ${api.path}${api.description ? " — " + api.description : ""}`,
    request: {
      method: api.method,
      header: headers,
      url: {
        raw:
          (url.protocol ? url.protocol + "://" : "") +
          url.host.join("") +
          (url.path.length ? "/" + url.path.join("/") : ""),
        host: url.host,
        path: url.path,
        ...(url.protocol ? { protocol: url.protocol } : {}),
      },
    },
    event: [
      {
        listen: "test",
        script: { exec: buildAssertions(api), type: "text/javascript" },
      },
    ],
  };
  const body = buildRequestBody(api);
  if (body) item.request.body = body;
  return item;
}

export function apisToPostmanCollection(apis, { name = "Generated from stories.xlsx" } = {}) {
  const items = (apis || []).map(apiToPostmanItem).filter(Boolean);
  return {
    info: {
      _postman_id: "stories-import-" + Date.now(),
      name,
      description: "Auto-generated by repo-qa-agent stories from an APIs sheet.",
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
    },
    variable: [
      { key: "apiHost", value: "https://api.example.com" },
      { key: "authToken", value: "", description: "Bearer token; populated by the auth step" },
    ],
    item: items,
  };
}
