/**
 * Autonomous UAT walker.
 *
 * Drives a real Playwright session through a flow starting from a given
 * UAT entry URL. At each step the walker:
 *   1. Snapshots the page (accessible names of inputs + buttons)
 *   2. Fills any form field whose label/name/placeholder matches a fixture key
 *   3. Picks the highest-priority CTA from a configurable list
 *      (PROCEED, Continue, Submit, Next, BUY NOW, Confirm)
 *   4. Clicks it, waits for a URL change or DOM stabilization
 *   5. Records the transition
 *
 * Terminates when: max-steps hit, no CTA found, URL stops changing, the
 * page asks for an OTP we can't bypass, or a captcha is detected.
 *
 * Each call to walkJourney() returns one trace — UAT-URL lists are
 * orchestrated in the CLI by calling walkJourney() once per URL.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";

const DEFAULT_CTA_PRIORITIES = [
  "PROCEED",
  "Continue",
  "Submit",
  "Next",
  "BUY NOW",
  "Confirm",
  "Save",
  "Pay",
];

const OTP_INPUT_RE = /\b(otp|verification.?code|one.?time|code)\b/i;
const OTP_BUTTON_RE = /\b(validate|verify|submit code)\b/i;
const CAPTCHA_HINT_RE =
  /\b(captcha|i'?m not a robot|recaptcha|hcaptcha|verify you are human)\b/i;

// ---------- Pure helpers (testable without a browser) ----------

/**
 * Score buttons by where their label appears in the priority list.
 * Lower index = higher priority. Ties broken by document order (first wins).
 * Returns the chosen button or null.
 */
export function chooseCta(buttons, priorities = DEFAULT_CTA_PRIORITIES) {
  if (!buttons?.length) return null;
  const lowerPrios = priorities.map((p) => p.toLowerCase());
  const ranked = buttons
    .map((btn, idx) => {
      const label = String(btn.label || "").trim().toLowerCase();
      const matchIdx = lowerPrios.findIndex((p) => label === p.toLowerCase() || label.includes(p.toLowerCase()));
      return { btn, idx, matchIdx };
    })
    .filter((entry) => entry.matchIdx >= 0)
    .sort((a, b) => (a.matchIdx - b.matchIdx) || (a.idx - b.idx));
  if (ranked.length) return ranked[0].btn;
  // Fallback: first visible button whose label isn't "Back" or "Cancel"
  const fallback = buttons.find((b) => {
    const l = String(b.label || "").trim().toLowerCase();
    return l && !/^(back|cancel|close|skip|previous)$/i.test(l);
  });
  return fallback || null;
}

/**
 * Match each field in the page snapshot to a value from the fixture.
 * Resolution order per field: label → name → placeholder → aria-label.
 * Fixture lookup is case-insensitive on the same identifiers.
 */
export function matchFieldsToFixture(fields, fixture) {
  const fills = fixture?.formFills || {};
  const lookup = {};
  for (const [k, v] of Object.entries(fills)) lookup[k.toLowerCase()] = v;

  const matches = [];
  for (const field of fields || []) {
    const keys = [field.label, field.name, field.placeholder, field.ariaLabel]
      .map((s) => (s ? String(s).toLowerCase() : null))
      .filter(Boolean);
    let hit = null;
    for (const k of keys) {
      if (lookup[k] !== undefined) {
        hit = lookup[k];
        break;
      }
    }
    if (hit !== null) {
      matches.push({ field, value: hit });
    }
  }
  return matches;
}

/** Detect whether the current snapshot represents an OTP gate. */
export function isOtpGate(snapshot) {
  if (!snapshot) return false;
  const hasOtpInput = (snapshot.fields || []).some(
    (f) => OTP_INPUT_RE.test(`${f.label} ${f.name} ${f.placeholder} ${f.ariaLabel}`)
  );
  const hasValidate = (snapshot.buttons || []).some(
    (b) => OTP_BUTTON_RE.test(b.label || "")
  );
  return hasOtpInput && hasValidate;
}

export function isCaptcha(snapshot) {
  if (!snapshot?.text) return false;
  return CAPTCHA_HINT_RE.test(snapshot.text);
}

/**
 * Build a Playwright spec from a recorded trace. The output reproduces
 * the walk: navigate to entryUrl, for each stage fill the same fields and
 * click the same CTA, asserting the next URL each time.
 */
export function buildSpecFromTrace(trace, { specName = "walked-journey" } = {}) {
  const lines = [];
  lines.push(`import { test, expect } from '@playwright/test';`);
  lines.push(``);
  lines.push(`// Generated by repo-qa-agent walk on ${trace.startedAt || new Date().toISOString()}`);
  lines.push(`// Reproduces the autonomous walk from ${JSON.stringify(trace.entryUrl)}.`);
  lines.push(`// Last URL: ${trace.terminalUrl}. Termination: ${trace.terminationReason}.`);
  lines.push(``);
  lines.push(`test('walked journey: ${specName}', async ({ page }) => {`);
  lines.push(`  await page.goto(${JSON.stringify(trace.entryUrl)}, { waitUntil: 'domcontentloaded' });`);
  for (const stage of trace.stages || []) {
    if (stage.skipped) continue;
    if (stage.filledFields?.length) {
      for (const f of stage.filledFields) {
        const accessor = f.label
          ? `getByLabel(${JSON.stringify(f.label)})`
          : f.name
            ? `locator('[name=${JSON.stringify(f.name)}]')`
            : null;
        if (!accessor) continue;
        lines.push(`  await page.${accessor}.fill(${JSON.stringify(String(f.value))});`);
      }
    }
    if (stage.ctaClicked?.label) {
      lines.push(`  await page.getByRole('button', { name: ${JSON.stringify(stage.ctaClicked.label)} }).first().click();`);
    }
    if (stage.transition?.toUrl) {
      const urlPattern = stage.transition.toUrl.replace(/[?]/g, "\\?");
      lines.push(`  await expect(page).toHaveURL(/${escapeForRegex(stage.transition.toUrl)}/, { timeout: 30_000 });`);
    }
  }
  lines.push(`});`);
  lines.push(``);
  return lines.join("\n");
}

function escapeForRegex(s) {
  return String(s).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ---------- I/O wrapper (drives a real or injected browser) ----------

/**
 * Snapshot the page into a structured form the pure helpers can consume.
 * Pulled out so tests can inject fake snapshots.
 */
async function snapshotPage(page) {
  const data = await page.evaluate(() => {
    function visible(el) {
      if (!el) return false;
      const style = window.getComputedStyle(el);
      if (style.display === "none" || style.visibility === "hidden" || style.opacity === "0") return false;
      const rect = el.getBoundingClientRect();
      return rect.width > 0 && rect.height > 0;
    }
    function accName(el) {
      if (!el) return "";
      const aria = el.getAttribute("aria-label");
      if (aria) return aria.trim();
      const labelledBy = el.getAttribute("aria-labelledby");
      if (labelledBy) {
        const label = document.getElementById(labelledBy);
        if (label) return (label.textContent || "").trim();
      }
      if (el.id) {
        const label = document.querySelector('label[for="' + el.id + '"]');
        if (label) return (label.textContent || "").trim();
      }
      const wrap = el.closest("label");
      if (wrap) return (wrap.textContent || "").trim();
      return "";
    }
    const fields = [];
    for (const el of Array.from(document.querySelectorAll("input, select, textarea"))) {
      if (!visible(el)) continue;
      const type = (el.getAttribute("type") || el.tagName || "").toLowerCase();
      if (type === "hidden" || type === "submit" || type === "button") continue;
      fields.push({
        label: accName(el),
        name: el.getAttribute("name") || "",
        placeholder: el.getAttribute("placeholder") || "",
        ariaLabel: el.getAttribute("aria-label") || "",
        type,
        disabled: el.disabled === true,
      });
    }
    const buttons = [];
    const selector = 'button, [role="button"], a[role="button"]';
    for (const el of Array.from(document.querySelectorAll(selector))) {
      if (!visible(el)) continue;
      if (el.disabled === true) continue;
      const label = (el.innerText || el.textContent || accName(el) || "").trim().replace(/\s+/g, " ");
      if (!label) continue;
      buttons.push({ label, role: "button" });
    }
    return { fields, buttons, text: (document.body?.innerText || "").slice(0, 4000) };
  });
  return data;
}

async function fillField(page, field, value) {
  if (field.label) {
    try {
      await page.getByLabel(field.label, { exact: false }).first().fill(String(value));
      return true;
    } catch {}
  }
  if (field.name) {
    try {
      await page.locator(`[name="${field.name}"]`).first().fill(String(value));
      return true;
    } catch {}
  }
  return false;
}

async function clickButtonByLabel(page, label) {
  try {
    await page.getByRole("button", { name: label }).first().click();
    return true;
  } catch {
    try {
      await page.getByText(label, { exact: false }).first().click();
      return true;
    } catch {
      return false;
    }
  }
}

async function waitForTransition(page, beforeUrl, timeoutMs = 30_000) {
  const started = Date.now();
  while (Date.now() - started < timeoutMs) {
    const url = page.url();
    if (url !== beforeUrl) {
      return { toUrl: url, urlChanged: true, elapsedMs: Date.now() - started };
    }
    await page.waitForTimeout(250);
  }
  return { toUrl: page.url(), urlChanged: false, elapsedMs: Date.now() - started };
}

/** Resolve `playwright` lazily so the rest of the agent's tooling doesn't fail when chromium isn't installed. */
async function launchBrowser({ headless = true }) {
  const { chromium } = await import("playwright");
  return chromium.launch({ headless });
}

/**
 * Walk a single journey from an entry URL. Returns the trace.
 * Caller is responsible for orchestrating multiple walks (per-URL).
 */
export async function walkJourney({
  entryUrl,
  fixture = {},
  maxSteps = 10,
  ctaPriorities = DEFAULT_CTA_PRIORITIES,
  stopWhen,
  headless = true,
  page: injectedPage,
  logger = () => {},
  navigationTimeoutMs = 30_000,
} = {}) {
  if (!entryUrl) throw new Error("walkJourney: entryUrl is required");
  const stopWhenRe = stopWhen instanceof RegExp ? stopWhen : (typeof stopWhen === "string" ? new RegExp(stopWhen) : null);

  const trace = {
    entryUrl,
    startedAt: new Date().toISOString(),
    fixtureKeys: Object.keys(fixture?.formFills || {}),
    stages: [],
    terminalUrl: null,
    terminationReason: null,
    steps: 0,
  };

  let browser = null;
  let context = null;
  let page = injectedPage;
  try {
    if (!page) {
      browser = await launchBrowser({ headless });
      context = await browser.newContext();
      page = await context.newPage();
    }

    await page.goto(entryUrl, { waitUntil: "domcontentloaded", timeout: navigationTimeoutMs });

    for (let step = 0; step < maxSteps; step++) {
      trace.steps = step + 1;
      const currentUrl = page.url();
      logger(`step ${step}: ${currentUrl}`);

      if (stopWhenRe && stopWhenRe.test(currentUrl)) {
        trace.stages.push({ step, url: currentUrl, terminated: "matched stopWhen" });
        trace.terminationReason = "matched stopWhen";
        trace.terminalUrl = currentUrl;
        break;
      }

      const snapshot = await snapshotPage(page);
      const stage = {
        step,
        url: currentUrl,
        title: await page.title().catch(() => ""),
        snapshot,
      };

      if (isCaptcha(snapshot)) {
        stage.terminated = "captcha detected";
        trace.terminationReason = "captcha detected";
        trace.terminalUrl = currentUrl;
        trace.stages.push(stage);
        break;
      }

      if (isOtpGate(snapshot)) {
        const otpValue = fixture?.auth?.otpBypass;
        if (!otpValue) {
          stage.terminated = "OTP required, no fixture.auth.otpBypass";
          trace.terminationReason = "OTP required";
          trace.terminalUrl = currentUrl;
          trace.stages.push(stage);
          break;
        }
        const otpField = snapshot.fields.find((f) =>
          OTP_INPUT_RE.test(`${f.label} ${f.name} ${f.placeholder} ${f.ariaLabel}`)
        );
        if (otpField) {
          await fillField(page, otpField, otpValue);
          stage.otpFilled = true;
        }
      }

      const fieldsToFill = matchFieldsToFixture(snapshot.fields, fixture);
      const filledFields = [];
      for (const { field, value } of fieldsToFill) {
        if (field.disabled) continue;
        const ok = await fillField(page, field, value);
        if (ok) filledFields.push({ label: field.label, name: field.name, value });
      }
      stage.filledFields = filledFields;

      const cta = chooseCta(snapshot.buttons, ctaPriorities);
      if (!cta) {
        stage.terminated = "no CTA found";
        trace.terminationReason = "no CTA found";
        trace.terminalUrl = currentUrl;
        trace.stages.push(stage);
        break;
      }
      stage.ctaClicked = { label: cta.label };

      const beforeUrl = currentUrl;
      const clicked = await clickButtonByLabel(page, cta.label);
      if (!clicked) {
        stage.terminated = `failed to click CTA "${cta.label}"`;
        trace.terminationReason = `click failed`;
        trace.terminalUrl = currentUrl;
        trace.stages.push(stage);
        break;
      }

      const transition = await waitForTransition(page, beforeUrl);
      stage.transition = transition;
      trace.stages.push(stage);

      if (!transition.urlChanged) {
        trace.terminationReason = "URL did not change after CTA";
        trace.terminalUrl = transition.toUrl;
        break;
      }
    }

    if (!trace.terminationReason) {
      trace.terminationReason = "max-steps reached";
      trace.terminalUrl = page.url();
    }
  } finally {
    if (browser) await browser.close().catch(() => {});
  }

  trace.endedAt = new Date().toISOString();
  return trace;
}

/**
 * Convenience: write a trace JSON to disk. Used by the CLI.
 */
export function writeTrace(trace, outPath) {
  mkdirSync(path.dirname(path.resolve(outPath)), { recursive: true });
  writeFileSync(outPath, JSON.stringify(trace, null, 2) + "\n", "utf8");
  return path.resolve(outPath);
}
